.PHONY: clean rebuild debug

SRCS_DIRS:=./src
INCL_DIRS:=./include
BIN_DIRS:=./bin
SRCS:= $(wildcard $(SRCS_DIRS)/*.c)
OBJS:= $(patsubst $(SRCS_DIRS)/%.c,$(BIN_DIRS)/%.o,$(SRCS))






show:
	@echo $(SRCS)
	@echo $(OBJS)


rebuild:

debug:


clean:

